version: '3'

services:
  blog:
    container_name: blog
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:14.2
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: blog
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  dbdata: