spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    driver-class-name: org.postgresql.Driver
    username: maximdziuba
    password: behama25
  sql:
    init:
      mode: always
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 259086280795-2824jsornars0c412gcprj32fts2cbr7.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

app:
  view:
    number-of-elements-in-row: 2