spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://db:5432/blog
    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: behama25
    username: user
    password: pass
  sql:
    init:
      mode: always
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: # enter here your client-id from console.cloug.google.com
            client-secret: # enter here your client-secret from console.cloug.google.com

app:
  view:
    number-of-elements-in-row: 2